[package]
name = "kosmetic_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kosmetic_zx = { path = "../kosmetic_zx", default-features = false }

[features]
tracing = ["kosmetic_zx/trace-all"]